// Additional ship roster — ~100 ships with varied sizes and job roles
// Organized by manufacturer, spanning classes 1-4

export const ADDITIONAL_SHIPS = [
  // === Falcon Delacy — birds of prey, multipurpose/trader ===
  { id: 'sparrow', name: 'Sparrow', manufacturer: 'Falcon Delacy', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 9, cost: 12000, multirole: true, class: 1 },
  { id: 'kestrel_mk1', name: 'Kestrel Mk-I', manufacturer: 'Falcon Delacy', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 8, cost: 38000, multirole: false, class: 1 },
  { id: 'merlin', name: 'Merlin Interceptor', manufacturer: 'Falcon Delacy', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 10, cost: 52000, multirole: false, class: 1 },
  { id: 'kite', name: 'Kite Light Hauler', manufacturer: 'Falcon Delacy', cargoCapacity: 10, fuelCapacity: 8, jumpRange: 11, cost: 88000, multirole: true, class: 1 },
  { id: 'osprey_mk2', name: 'Osprey Mk-II', manufacturer: 'Falcon Delacy', cargoCapacity: 14, fuelCapacity: 16, jumpRange: 19, cost: 1800000, multirole: true, class: 2 },
  { id: 'harrier_base', name: 'Harrier', manufacturer: 'Falcon Delacy', cargoCapacity: 16, fuelCapacity: 32, jumpRange: 17, cost: 3200000, multirole: true, class: 2 },
  { id: 'goshawk', name: 'Goshawk Trader', manufacturer: 'Falcon Delacy', cargoCapacity: 24, fuelCapacity: 16, jumpRange: 14, cost: 4200000, multirole: false, class: 2 },
  { id: 'buzzard', name: 'Buzzard Miner', manufacturer: 'Falcon Delacy', cargoCapacity: 18, fuelCapacity: 16, jumpRange: 13, cost: 3900000, multirole: false, class: 2 },
  { id: 'kite_mk2', name: 'Kite Mk-II', manufacturer: 'Falcon Delacy', cargoCapacity: 14, fuelCapacity: 16, jumpRange: 13, cost: 780000, multirole: true, class: 2 },
  { id: 'harrier_mk3', name: 'Harrier Mk-III', manufacturer: 'Falcon Delacy', cargoCapacity: 20, fuelCapacity: 32, jumpRange: 18, cost: 4800000, multirole: true, class: 2 },
  { id: 'eagle_mk3', name: 'Peregrine Mk-III', manufacturer: 'Falcon Delacy', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 10, cost: 620000, multirole: false, class: 2 },
  { id: 'gyr_falcon', name: 'Gyr Falcon', manufacturer: 'Falcon Delacy', cargoCapacity: 48, fuelCapacity: 32, jumpRange: 15, cost: 38000000, multirole: true, class: 3 },
  { id: 'peregrine_mk3', name: 'Goshawk Mk-III', manufacturer: 'Falcon Delacy', cargoCapacity: 6, fuelCapacity: 32, jumpRange: 12, cost: 22000000, multirole: false, class: 3 },
  { id: 'honey_buzzard', name: 'Honey Buzzard', manufacturer: 'Falcon Delacy', cargoCapacity: 64, fuelCapacity: 32, jumpRange: 14, cost: 45000000, multirole: false, class: 3 },
  { id: 'red_kite', name: 'Red Kite Explorer', manufacturer: 'Falcon Delacy', cargoCapacity: 22, fuelCapacity: 32, jumpRange: 21, cost: 29000000, multirole: true, class: 3 },
  { id: 'gyrfalcon', name: 'Gyrfalcon', manufacturer: 'Falcon Delacy', cargoCapacity: 52, fuelCapacity: 32, jumpRange: 16, cost: 52000000, multirole: true, class: 3 },
  { id: 'lammergeier', name: 'Lammergeier', manufacturer: 'Falcon Delacy', cargoCapacity: 140, fuelCapacity: 64, jumpRange: 14, cost: 92000000, multirole: false, class: 4 },
  { id: 'sea_eagle', name: 'Sea Eagle', manufacturer: 'Falcon Delacy', cargoCapacity: 96, fuelCapacity: 64, jumpRange: 17, cost: 110000000, multirole: true, class: 4 },
  { id: 'golden_eagle', name: 'Golden Eagle', manufacturer: 'Falcon Delacy', cargoCapacity: 24, fuelCapacity: 64, jumpRange: 15, cost: 165000000, multirole: false, class: 4 },
  { id: 'roc_mk2', name: 'Roc Mk-II', manufacturer: 'Falcon Delacy', cargoCapacity: 120, fuelCapacity: 64, jumpRange: 19, cost: 180000000, multirole: true, class: 4 },

  // === Lakon Spaceways — industrial/cargo ===
  { id: 'mule', name: 'Mule', manufacturer: 'Lakon Spaceways', cargoCapacity: 6, fuelCapacity: 8, jumpRange: 9, cost: 44000, multirole: false, class: 1 },
  { id: 'cart_horse', name: 'Cart Horse', manufacturer: 'Lakon Spaceways', cargoCapacity: 8, fuelCapacity: 8, jumpRange: 8, cost: 62000, multirole: false, class: 1 },
  { id: 'packmule_mk2', name: 'Packmule Mk-II', manufacturer: 'Lakon Spaceways', cargoCapacity: 26, fuelCapacity: 16, jumpRange: 11, cost: 78000, multirole: false, class: 2 },
  { id: 'caravan_mk4', name: 'Caravan Mk-IV', manufacturer: 'Lakon Spaceways', cargoCapacity: 34, fuelCapacity: 16, jumpRange: 13, cost: 580000, multirole: false, class: 2 },
  { id: 'dray', name: 'Dray Hauler', manufacturer: 'Lakon Spaceways', cargoCapacity: 30, fuelCapacity: 16, jumpRange: 12, cost: 720000, multirole: false, class: 2 },
  { id: 'wagon', name: 'Wagon Freighter', manufacturer: 'Lakon Spaceways', cargoCapacity: 40, fuelCapacity: 32, jumpRange: 14, cost: 2800000, multirole: false, class: 2 },
  { id: 'caravan_mk6b', name: 'Caravan Mk-VIb', manufacturer: 'Lakon Spaceways', cargoCapacity: 56, fuelCapacity: 32, jumpRange: 15, cost: 1800000, multirole: false, class: 2 },
  { id: 'cart_horse_mk2', name: 'Cart Horse Mk-II', manufacturer: 'Lakon Spaceways', cargoCapacity: 16, fuelCapacity: 16, jumpRange: 12, cost: 340000, multirole: true, class: 2 },
  { id: 'ox', name: 'Ox Heavy Hauler', manufacturer: 'Lakon Spaceways', cargoCapacity: 88, fuelCapacity: 32, jumpRange: 13, cost: 15000000, multirole: false, class: 3 },
  { id: 'barge', name: 'Barge Bulk Carrier', manufacturer: 'Lakon Spaceways', cargoCapacity: 120, fuelCapacity: 32, jumpRange: 11, cost: 28000000, multirole: false, class: 3 },
  { id: 'tug', name: 'Salvage Tug', manufacturer: 'Lakon Spaceways', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 12, cost: 8500000, multirole: false, class: 3 },
  { id: 'dredger', name: 'Dredger Miner', manufacturer: 'Lakon Spaceways', cargoCapacity: 72, fuelCapacity: 32, jumpRange: 10, cost: 22000000, multirole: false, class: 3 },
  { id: 'freighter', name: 'Freighter', manufacturer: 'Lakon Spaceways', cargoCapacity: 104, fuelCapacity: 32, jumpRange: 12, cost: 34000000, multirole: false, class: 3 },
  { id: 'ox_mk2', name: 'Ox Mk-II', manufacturer: 'Lakon Spaceways', cargoCapacity: 100, fuelCapacity: 32, jumpRange: 14, cost: 42000000, multirole: false, class: 3 },
  { id: 'caravan_mk7b', name: 'Caravan Mk-VIIb', manufacturer: 'Lakon Spaceways', cargoCapacity: 108, fuelCapacity: 32, jumpRange: 15, cost: 25000000, multirole: false, class: 3 },
  { id: 'leviathan_lk', name: 'Leviathan', manufacturer: 'Lakon Spaceways', cargoCapacity: 240, fuelCapacity: 64, jumpRange: 10, cost: 95000000, multirole: false, class: 4 },
  { id: 'mammoth', name: 'Mammoth Hauler', manufacturer: 'Lakon Spaceways', cargoCapacity: 200, fuelCapacity: 64, jumpRange: 11, cost: 88000000, multirole: false, class: 4 },
  { id: 'goliath', name: 'Goliath Industrial', manufacturer: 'Lakon Spaceways', cargoCapacity: 180, fuelCapacity: 64, jumpRange: 9, cost: 72000000, multirole: false, class: 4 },
  { id: 'titan_hauler', name: 'Titan Hauler', manufacturer: 'Lakon Spaceways', cargoCapacity: 260, fuelCapacity: 64, jumpRange: 12, cost: 130000000, multirole: false, class: 4 },
  { id: 'behemoth', name: 'Behemoth', manufacturer: 'Lakon Spaceways', cargoCapacity: 320, fuelCapacity: 64, jumpRange: 8, cost: 155000000, multirole: false, class: 4 },

  // === Core Dynamics — military/combat ===
  { id: 'falconet', name: 'Falconet Interceptor', manufacturer: 'Core Dynamics', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 10, cost: 58000, multirole: false, class: 1 },
  { id: 'saker', name: 'Saker Patrol', manufacturer: 'Core Dynamics', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 9, cost: 88000, multirole: false, class: 1 },
  { id: 'tiercel', name: 'Tiercel Recon', manufacturer: 'Core Dynamics', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 12, cost: 72000, multirole: false, class: 1 },
  { id: 'lance', name: 'Lance Assault', manufacturer: 'Core Dynamics', cargoCapacity: 8, fuelCapacity: 16, jumpRange: 11, cost: 3800000, multirole: false, class: 2 },
  { id: 'phalanx', name: 'Phalanx Gunship', manufacturer: 'Core Dynamics', cargoCapacity: 6, fuelCapacity: 16, jumpRange: 10, cost: 4600000, multirole: false, class: 2 },
  { id: 'vanguard_mk2', name: 'Republic Vanguard Mk-II', manufacturer: 'Core Dynamics', cargoCapacity: 6, fuelCapacity: 32, jumpRange: 13, cost: 24000000, multirole: false, class: 3 },
  { id: 'centurion', name: 'Centurion Patrol', manufacturer: 'Core Dynamics', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 14, cost: 18000000, multirole: false, class: 3 },
  { id: 'legionary', name: 'Legionary Transport', manufacturer: 'Core Dynamics', cargoCapacity: 16, fuelCapacity: 32, jumpRange: 12, cost: 16000000, multirole: false, class: 3 },
  { id: 'praetor', name: 'Praetor Gunship', manufacturer: 'Core Dynamics', cargoCapacity: 8, fuelCapacity: 32, jumpRange: 12, cost: 28000000, multirole: false, class: 3 },
  { id: 'tribune', name: 'Tribune Command', manufacturer: 'Core Dynamics', cargoCapacity: 14, fuelCapacity: 32, jumpRange: 13, cost: 32000000, multirole: true, class: 3 },
  { id: 'cataphract', name: 'Cataphract', manufacturer: 'Core Dynamics', cargoCapacity: 20, fuelCapacity: 64, jumpRange: 14, cost: 140000000, multirole: false, class: 4 },
  { id: 'ballista', name: 'Ballista Siege', manufacturer: 'Core Dynamics', cargoCapacity: 12, fuelCapacity: 64, jumpRange: 13, cost: 170000000, multirole: false, class: 4 },
  { id: 'citadel', name: 'Citadel Flagship', manufacturer: 'Core Dynamics', cargoCapacity: 32, fuelCapacity: 64, jumpRange: 15, cost: 200000000, multirole: true, class: 4 },
  { id: 'bulwark', name: 'Bulwark Defense', manufacturer: 'Core Dynamics', cargoCapacity: 24, fuelCapacity: 64, jumpRange: 12, cost: 155000000, multirole: false, class: 4 },
  { id: 'aegis', name: 'Aegis Command', manufacturer: 'Core Dynamics', cargoCapacity: 28, fuelCapacity: 64, jumpRange: 14, cost: 185000000, multirole: true, class: 4 },

  // === Zorgon Peterson — specialized/explorer ===
  { id: 'tern', name: 'Tern Scout', manufacturer: 'Zorgon Peterson', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 12, cost: 68000, multirole: true, class: 1 },
  { id: 'petrel', name: 'Petrel Explorer', manufacturer: 'Zorgon Peterson', cargoCapacity: 6, fuelCapacity: 8, jumpRange: 14, cost: 92000, multirole: true, class: 1 },
  { id: 'skua', name: 'Skua Combat', manufacturer: 'Zorgon Peterson', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 11, cost: 2800000, multirole: false, class: 2 },
  { id: 'albatross_jr', name: 'Albatross Jr', manufacturer: 'Zorgon Peterson', cargoCapacity: 18, fuelCapacity: 32, jumpRange: 20, cost: 4200000, multirole: true, class: 2 },
  { id: 'booby', name: 'Booby Survey', manufacturer: 'Zorgon Peterson', cargoCapacity: 12, fuelCapacity: 16, jumpRange: 16, cost: 2200000, multirole: true, class: 2 },
  { id: 'jaeger', name: 'Jaeger Recon', manufacturer: 'Zorgon Peterson', cargoCapacity: 8, fuelCapacity: 16, jumpRange: 18, cost: 3600000, multirole: false, class: 2 },
  { id: 'tern_mk2', name: 'Tern Mk-II', manufacturer: 'Zorgon Peterson', cargoCapacity: 16, fuelCapacity: 32, jumpRange: 22, cost: 8800000, multirole: true, class: 2 },
  { id: 'skimmer', name: 'Skimmer Support', manufacturer: 'Zorgon Peterson', cargoCapacity: 10, fuelCapacity: 16, jumpRange: 15, cost: 2400000, multirole: true, class: 2 },
  { id: 'petrel_mk2', name: 'Petrel Mk-II', manufacturer: 'Zorgon Peterson', cargoCapacity: 20, fuelCapacity: 32, jumpRange: 24, cost: 16000000, multirole: true, class: 3 },
  { id: 'jaeger_mk2', name: 'Jaeger Mk-II', manufacturer: 'Zorgon Peterson', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 20, cost: 14000000, multirole: false, class: 3 },
  { id: 'albatross_explorer', name: 'Albatross Explorer', manufacturer: 'Zorgon Peterson', cargoCapacity: 28, fuelCapacity: 32, jumpRange: 26, cost: 34000000, multirole: true, class: 3 },
  { id: 'wanderer_mk2', name: 'Wanderer Mk-II', manufacturer: 'Zorgon Peterson', cargoCapacity: 24, fuelCapacity: 32, jumpRange: 25, cost: 28000000, multirole: true, class: 3 },

  // === Saud Kruger — passenger/luxury ===
  { id: 'porpoise', name: 'Porpoise', manufacturer: 'Saud Kruger', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 14, cost: 1200000, multirole: false, class: 2 },
  { id: 'dolphin_mk2', name: 'Narwhal Mk-II', manufacturer: 'Saud Kruger', cargoCapacity: 8, fuelCapacity: 16, jumpRange: 16, cost: 2800000, multirole: true, class: 2 },
  { id: 'beluga_jr', name: 'Beluga Jr', manufacturer: 'Saud Kruger', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 15, cost: 28000000, multirole: false, class: 3 },
  { id: 'narwhal_mk2', name: 'Narwhal Mk-III', manufacturer: 'Saud Kruger', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 17, cost: 32000000, multirole: false, class: 3 },
  { id: 'cachalot_mk2', name: 'Cachalot Mk-II', manufacturer: 'Saud Kruger', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 16, cost: 38000000, multirole: false, class: 3 },
  { id: 'manatee', name: 'Manatee', manufacturer: 'Saud Kruger', cargoCapacity: 14, fuelCapacity: 32, jumpRange: 14, cost: 36000000, multirole: false, class: 3 },
  { id: 'orca_mk2', name: 'Cachalot Mk-III', manufacturer: 'Saud Kruger', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 17, cost: 52000000, multirole: false, class: 3 },
  { id: 'leviathan_liner', name: 'Leviathan Liner Mk-II', manufacturer: 'Saud Kruger', cargoCapacity: 16, fuelCapacity: 64, jumpRange: 16, cost: 92000000, multirole: false, class: 4 },
  { id: 'blue_whale', name: 'Blue Whale', manufacturer: 'Saud Kruger', cargoCapacity: 20, fuelCapacity: 64, jumpRange: 14, cost: 120000000, multirole: false, class: 4 },
  { id: 'royal_narwhal', name: 'Royal Narwhal', manufacturer: 'Saud Kruger', cargoCapacity: 18, fuelCapacity: 64, jumpRange: 18, cost: 140000000, multirole: false, class: 4 },

  // === Gutamaya — imperial ===
  { id: 'imperial_eagle', name: 'Imperial Eagle', manufacturer: 'Gutamaya', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 11, cost: 58000, multirole: false, class: 1 },
  { id: 'dynast_scout', name: 'Dynast Scout', manufacturer: 'Gutamaya', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 13, cost: 82000, multirole: true, class: 1 },
  { id: 'dynast_courier_mk2', name: 'Dynast Courier Mk-II', manufacturer: 'Gutamaya', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 14, cost: 6200000, multirole: true, class: 2 },
  { id: 'imperial_hawk', name: 'Imperial Hawk', manufacturer: 'Gutamaya', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 12, cost: 4800000, multirole: false, class: 2 },
  { id: 'dynast_shuttle', name: 'Dynast Shuttle', manufacturer: 'Gutamaya', cargoCapacity: 12, fuelCapacity: 16, jumpRange: 13, cost: 2600000, multirole: false, class: 2 },
  { id: 'imperial_falcon', name: 'Imperial Falcon', manufacturer: 'Gutamaya', cargoCapacity: 8, fuelCapacity: 32, jumpRange: 14, cost: 5800000, multirole: false, class: 2 },
  { id: 'dynast_clipper_mk2', name: 'Dynast Clipper Mk-II', manufacturer: 'Gutamaya', cargoCapacity: 38, fuelCapacity: 32, jumpRange: 15, cost: 28000000, multirole: true, class: 3 },
  { id: 'imperial_raven', name: 'Imperial Raven', manufacturer: 'Gutamaya', cargoCapacity: 8, fuelCapacity: 32, jumpRange: 13, cost: 26000000, multirole: false, class: 3 },
  { id: 'dynast_palace', name: 'Dynast Palace', manufacturer: 'Gutamaya', cargoCapacity: 16, fuelCapacity: 32, jumpRange: 15, cost: 62000000, multirole: false, class: 3 },
  { id: 'dynast_sovereign_mk2', name: 'Dynast Sovereign Mk-II', manufacturer: 'Gutamaya', cargoCapacity: 130, fuelCapacity: 64, jumpRange: 17, cost: 240000000, multirole: true, class: 4 },

  // === Coalition / Alliance ===
  { id: 'coalition_scout', name: 'Coalition Scout', manufacturer: 'Lakon Spaceways', cargoCapacity: 8, fuelCapacity: 16, jumpRange: 18, cost: 3200000, multirole: true, class: 2 },
  { id: 'coalition_fighter', name: 'Coalition Fighter', manufacturer: 'Lakon Spaceways', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 11, cost: 2800000, multirole: false, class: 2 },
  { id: 'coalition_ranger', name: 'Coalition Ranger', manufacturer: 'Lakon Spaceways', cargoCapacity: 36, fuelCapacity: 32, jumpRange: 16, cost: 24000000, multirole: true, class: 3 },
  { id: 'coalition_warden', name: 'Coalition Warden', manufacturer: 'Lakon Spaceways', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 13, cost: 22000000, multirole: false, class: 3 },
  { id: 'coalition_bastion', name: 'Coalition Bastion Mk-II', manufacturer: 'Lakon Spaceways', cargoCapacity: 140, fuelCapacity: 64, jumpRange: 11, cost: 110000000, multirole: false, class: 4 },

  // === Independent / Specialty ===
  { id: 'sirius_explorer', name: 'Sirius Explorer', manufacturer: 'Sirius Corp', cargoCapacity: 14, fuelCapacity: 32, jumpRange: 23, cost: 8800000, multirole: true, class: 2 },
  { id: 'omega_courier', name: 'Omega Courier', manufacturer: 'Omega Corp', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 13, cost: 48000, multirole: true, class: 1 },
  { id: 'sirius_trader', name: 'Sirius Trader', manufacturer: 'Sirius Corp', cargoCapacity: 48, fuelCapacity: 32, jumpRange: 15, cost: 26000000, multirole: false, class: 3 },
  { id: 'omega_interceptor', name: 'Omega Interceptor', manufacturer: 'Omega Corp', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 11, cost: 62000, multirole: false, class: 1 },
  { id: 'sirius_liner', name: 'Sirius Liner', manufacturer: 'Sirius Corp', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 16, cost: 34000000, multirole: false, class: 3 },
  { id: 'void_prospector', name: 'Void Prospector', manufacturer: 'Independent', cargoCapacity: 20, fuelCapacity: 16, jumpRange: 14, cost: 3600000, multirole: false, class: 2 },
  { id: 'star_drifter', name: 'Star Drifter', manufacturer: 'Independent', cargoCapacity: 30, fuelCapacity: 32, jumpRange: 24, cost: 38000000, multirole: true, class: 3 },
  { id: 'nova_hauler', name: 'Nova Hauler', manufacturer: 'Independent', cargoCapacity: 72, fuelCapacity: 32, jumpRange: 13, cost: 18000000, multirole: false, class: 3 },
];