// Additional ship roster — ~100 ships with varied sizes and job roles
// Organized by manufacturer, spanning classes 1-4
// Manufacturer names are original (not from Elite Dangerous)

export const ADDITIONAL_SHIPS = [
  // === Drake-Voss — birds of prey, multipurpose/trader ===
  { id: 'sparrow', name: 'Sparrow', manufacturer: 'Drake-Voss', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 9, cost: 12000, multirole: true, class: 1 },
  { id: 'kestrel_mk1', name: 'Shrike Mk-I', manufacturer: 'Drake-Voss', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 8, cost: 38000, multirole: false, class: 1 },
  { id: 'merlin', name: 'Merlin Interceptor', manufacturer: 'Drake-Voss', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 10, cost: 52000, multirole: false, class: 1 },
  { id: 'kite', name: 'Kite Light Freighter', manufacturer: 'Drake-Voss', cargoCapacity: 10, fuelCapacity: 8, jumpRange: 11, cost: 88000, multirole: true, class: 1 },
  { id: 'osprey_mk2', name: 'Osprey Mk-II', manufacturer: 'Drake-Voss', cargoCapacity: 14, fuelCapacity: 16, jumpRange: 19, cost: 1800000, multirole: true, class: 2 },
  { id: 'harrier_base', name: 'Harrier', manufacturer: 'Drake-Voss', cargoCapacity: 16, fuelCapacity: 32, jumpRange: 17, cost: 3200000, multirole: true, class: 2 },
  { id: 'goshawk', name: 'Goshawk Trader', manufacturer: 'Drake-Voss', cargoCapacity: 24, fuelCapacity: 16, jumpRange: 14, cost: 4200000, multirole: false, class: 2 },
  { id: 'buzzard', name: 'Buzzard Miner', manufacturer: 'Drake-Voss', cargoCapacity: 18, fuelCapacity: 16, jumpRange: 13, cost: 3900000, multirole: false, class: 2 },
  { id: 'kite_mk2', name: 'Kite Mk-II', manufacturer: 'Drake-Voss', cargoCapacity: 14, fuelCapacity: 16, jumpRange: 13, cost: 780000, multirole: true, class: 2 },
  { id: 'harrier_mk3', name: 'Harrier Mk-III', manufacturer: 'Drake-Voss', cargoCapacity: 20, fuelCapacity: 32, jumpRange: 18, cost: 4800000, multirole: true, class: 2 },
  { id: 'eagle_mk3', name: 'Peregrine Mk-III', manufacturer: 'Drake-Voss', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 10, cost: 620000, multirole: false, class: 2 },
  { id: 'gyr_falcon', name: 'Gyr Drake', manufacturer: 'Drake-Voss', cargoCapacity: 48, fuelCapacity: 32, jumpRange: 15, cost: 38000000, multirole: true, class: 3 },
  { id: 'peregrine_mk3', name: 'Goshawk Mk-III', manufacturer: 'Drake-Voss', cargoCapacity: 6, fuelCapacity: 32, jumpRange: 12, cost: 22000000, multirole: false, class: 3 },
  { id: 'honey_buzzard', name: 'Honey Buzzard', manufacturer: 'Drake-Voss', cargoCapacity: 64, fuelCapacity: 32, jumpRange: 14, cost: 45000000, multirole: false, class: 3 },
  { id: 'red_kite', name: 'Red Kite Surveyor', manufacturer: 'Drake-Voss', cargoCapacity: 22, fuelCapacity: 32, jumpRange: 21, cost: 29000000, multirole: true, class: 3 },
  { id: 'gyrfalcon', name: 'Gyrfalcon', manufacturer: 'Drake-Voss', cargoCapacity: 52, fuelCapacity: 32, jumpRange: 16, cost: 52000000, multirole: true, class: 3 },
  { id: 'lammergeier', name: 'Lammergeier', manufacturer: 'Drake-Voss', cargoCapacity: 140, fuelCapacity: 64, jumpRange: 14, cost: 92000000, multirole: false, class: 4 },
  { id: 'sea_eagle', name: 'Sea Hawk', manufacturer: 'Drake-Voss', cargoCapacity: 96, fuelCapacity: 64, jumpRange: 17, cost: 110000000, multirole: true, class: 4 },
  { id: 'golden_eagle', name: 'Golden Hawk', manufacturer: 'Drake-Voss', cargoCapacity: 24, fuelCapacity: 64, jumpRange: 15, cost: 165000000, multirole: false, class: 4 },
  { id: 'roc_mk2', name: 'Roc Mk-II', manufacturer: 'Drake-Voss', cargoCapacity: 120, fuelCapacity: 64, jumpRange: 19, cost: 180000000, multirole: true, class: 4 },

  // === Orion Heavy — industrial/cargo ===
  { id: 'mule', name: 'Mule', manufacturer: 'Orion Heavy', cargoCapacity: 6, fuelCapacity: 8, jumpRange: 9, cost: 44000, multirole: false, class: 1 },
  { id: 'cart_horse', name: 'Cart Horse', manufacturer: 'Orion Heavy', cargoCapacity: 8, fuelCapacity: 8, jumpRange: 8, cost: 62000, multirole: false, class: 1 },
  { id: 'packmule_mk2', name: 'Packmule Mk-II', manufacturer: 'Orion Heavy', cargoCapacity: 26, fuelCapacity: 16, jumpRange: 11, cost: 78000, multirole: false, class: 2 },
  { id: 'caravan_mk4', name: 'Caravan Mk-IV', manufacturer: 'Orion Heavy', cargoCapacity: 34, fuelCapacity: 16, jumpRange: 13, cost: 580000, multirole: false, class: 2 },
  { id: 'dray', name: 'Dray Freighter', manufacturer: 'Orion Heavy', cargoCapacity: 30, fuelCapacity: 16, jumpRange: 12, cost: 720000, multirole: false, class: 2 },
  { id: 'wagon', name: 'Wagon Freighter', manufacturer: 'Orion Heavy', cargoCapacity: 40, fuelCapacity: 32, jumpRange: 14, cost: 2800000, multirole: false, class: 2 },
  { id: 'caravan_mk6b', name: 'Caravan Mk-VIb', manufacturer: 'Orion Heavy', cargoCapacity: 56, fuelCapacity: 32, jumpRange: 15, cost: 1800000, multirole: false, class: 2 },
  { id: 'cart_horse_mk2', name: 'Cart Horse Mk-II', manufacturer: 'Orion Heavy', cargoCapacity: 16, fuelCapacity: 16, jumpRange: 12, cost: 340000, multirole: true, class: 2 },
  { id: 'ox', name: 'Ox Heavy Freighter', manufacturer: 'Orion Heavy', cargoCapacity: 88, fuelCapacity: 32, jumpRange: 13, cost: 15000000, multirole: false, class: 3 },
  { id: 'barge', name: 'Barge Bulk Carrier', manufacturer: 'Orion Heavy', cargoCapacity: 120, fuelCapacity: 32, jumpRange: 11, cost: 28000000, multirole: false, class: 3 },
  { id: 'tug', name: 'Salvage Tug', manufacturer: 'Orion Heavy', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 12, cost: 8500000, multirole: false, class: 3 },
  { id: 'dredger', name: 'Dredger Miner', manufacturer: 'Orion Heavy', cargoCapacity: 72, fuelCapacity: 32, jumpRange: 10, cost: 22000000, multirole: false, class: 3 },
  { id: 'freighter', name: 'Freighter', manufacturer: 'Orion Heavy', cargoCapacity: 104, fuelCapacity: 32, jumpRange: 12, cost: 34000000, multirole: false, class: 3 },
  { id: 'ox_mk2', name: 'Ox Mk-II', manufacturer: 'Orion Heavy', cargoCapacity: 100, fuelCapacity: 32, jumpRange: 14, cost: 42000000, multirole: false, class: 3 },
  { id: 'caravan_mk7b', name: 'Caravan Mk-VIIb', manufacturer: 'Orion Heavy', cargoCapacity: 108, fuelCapacity: 32, jumpRange: 15, cost: 25000000, multirole: false, class: 3 },
  { id: 'leviathan_lk', name: 'Leviathan', manufacturer: 'Orion Heavy', cargoCapacity: 240, fuelCapacity: 64, jumpRange: 10, cost: 95000000, multirole: false, class: 4 },
  { id: 'mammoth', name: 'Mammoth Freighter', manufacturer: 'Orion Heavy', cargoCapacity: 200, fuelCapacity: 64, jumpRange: 11, cost: 88000000, multirole: false, class: 4 },
  { id: 'goliath', name: 'Goliath Industrial', manufacturer: 'Orion Heavy', cargoCapacity: 180, fuelCapacity: 64, jumpRange: 9, cost: 72000000, multirole: false, class: 4 },
  { id: 'titan_hauler', name: 'Titan Freighter', manufacturer: 'Orion Heavy', cargoCapacity: 260, fuelCapacity: 64, jumpRange: 12, cost: 130000000, multirole: false, class: 4 },
  { id: 'behemoth', name: 'Behemoth', manufacturer: 'Orion Heavy', cargoCapacity: 320, fuelCapacity: 64, jumpRange: 8, cost: 155000000, multirole: false, class: 4 },

  // === Sentinel Forge — military/combat ===
  { id: 'falconet', name: 'Falconet Interceptor', manufacturer: 'Sentinel Forge', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 10, cost: 58000, multirole: false, class: 1 },
  { id: 'saker', name: 'Saker Patrol', manufacturer: 'Sentinel Forge', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 9, cost: 88000, multirole: false, class: 1 },
  { id: 'tiercel', name: 'Tiercel Recon', manufacturer: 'Sentinel Forge', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 12, cost: 72000, multirole: false, class: 1 },
  { id: 'lance', name: 'Lance Assault', manufacturer: 'Sentinel Forge', cargoCapacity: 8, fuelCapacity: 16, jumpRange: 11, cost: 3800000, multirole: false, class: 2 },
  { id: 'phalanx', name: 'Phalanx Gunship', manufacturer: 'Sentinel Forge', cargoCapacity: 6, fuelCapacity: 16, jumpRange: 10, cost: 4600000, multirole: false, class: 2 },
  { id: 'vanguard_mk2', name: 'Republic Vanguard Mk-II', manufacturer: 'Sentinel Forge', cargoCapacity: 6, fuelCapacity: 32, jumpRange: 13, cost: 24000000, multirole: false, class: 3 },
  { id: 'centurion', name: 'Centurion Patrol', manufacturer: 'Sentinel Forge', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 14, cost: 18000000, multirole: false, class: 3 },
  { id: 'legionary', name: 'Legionary Transport', manufacturer: 'Sentinel Forge', cargoCapacity: 16, fuelCapacity: 32, jumpRange: 12, cost: 16000000, multirole: false, class: 3 },
  { id: 'praetor', name: 'Praetor Gunship', manufacturer: 'Sentinel Forge', cargoCapacity: 8, fuelCapacity: 32, jumpRange: 12, cost: 28000000, multirole: false, class: 3 },
  { id: 'tribune', name: 'Tribune Command', manufacturer: 'Sentinel Forge', cargoCapacity: 14, fuelCapacity: 32, jumpRange: 13, cost: 32000000, multirole: true, class: 3 },
  { id: 'cataphract', name: 'Cataphract', manufacturer: 'Sentinel Forge', cargoCapacity: 20, fuelCapacity: 64, jumpRange: 14, cost: 140000000, multirole: false, class: 4 },
  { id: 'ballista', name: 'Ballista Siege', manufacturer: 'Sentinel Forge', cargoCapacity: 12, fuelCapacity: 64, jumpRange: 13, cost: 170000000, multirole: false, class: 4 },
  { id: 'citadel', name: 'Citadel Flagship', manufacturer: 'Sentinel Forge', cargoCapacity: 32, fuelCapacity: 64, jumpRange: 15, cost: 200000000, multirole: true, class: 4 },
  { id: 'bulwark', name: 'Bulwark Defense', manufacturer: 'Sentinel Forge', cargoCapacity: 24, fuelCapacity: 64, jumpRange: 12, cost: 155000000, multirole: false, class: 4 },
  { id: 'aegis', name: 'Aegis Command', manufacturer: 'Sentinel Forge', cargoCapacity: 28, fuelCapacity: 64, jumpRange: 14, cost: 185000000, multirole: true, class: 4 },

  // === Kepler Aeroworks — specialized/explorer ===
  { id: 'tern', name: 'Tern Pathfinder', manufacturer: 'Kepler Aeroworks', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 12, cost: 68000, multirole: true, class: 1 },
  { id: 'petrel', name: 'Petrel Surveyor', manufacturer: 'Kepler Aeroworks', cargoCapacity: 6, fuelCapacity: 8, jumpRange: 14, cost: 92000, multirole: true, class: 1 },
  { id: 'skua', name: 'Skua Combat', manufacturer: 'Kepler Aeroworks', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 11, cost: 2800000, multirole: false, class: 2 },
  { id: 'albatross_jr', name: 'Albatross Jr', manufacturer: 'Kepler Aeroworks', cargoCapacity: 18, fuelCapacity: 32, jumpRange: 20, cost: 4200000, multirole: true, class: 2 },
  { id: 'booby', name: 'Booby Survey', manufacturer: 'Kepler Aeroworks', cargoCapacity: 12, fuelCapacity: 16, jumpRange: 16, cost: 2200000, multirole: true, class: 2 },
  { id: 'jaeger', name: 'Jaeger Recon', manufacturer: 'Kepler Aeroworks', cargoCapacity: 8, fuelCapacity: 16, jumpRange: 18, cost: 3600000, multirole: false, class: 2 },
  { id: 'tern_mk2', name: 'Tern Mk-II', manufacturer: 'Kepler Aeroworks', cargoCapacity: 16, fuelCapacity: 32, jumpRange: 22, cost: 8800000, multirole: true, class: 2 },
  { id: 'skimmer', name: 'Skimmer Support', manufacturer: 'Kepler Aeroworks', cargoCapacity: 10, fuelCapacity: 16, jumpRange: 15, cost: 2400000, multirole: true, class: 2 },
  { id: 'petrel_mk2', name: 'Petrel Mk-II', manufacturer: 'Kepler Aeroworks', cargoCapacity: 20, fuelCapacity: 32, jumpRange: 24, cost: 16000000, multirole: true, class: 3 },
  { id: 'jaeger_mk2', name: 'Jaeger Mk-II', manufacturer: 'Kepler Aeroworks', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 20, cost: 14000000, multirole: false, class: 3 },
  { id: 'albatross_explorer', name: 'Albatross Surveyor', manufacturer: 'Kepler Aeroworks', cargoCapacity: 28, fuelCapacity: 32, jumpRange: 26, cost: 34000000, multirole: true, class: 3 },
  { id: 'wanderer_mk2', name: 'Wanderer Mk-II', manufacturer: 'Kepler Aeroworks', cargoCapacity: 24, fuelCapacity: 32, jumpRange: 25, cost: 28000000, multirole: true, class: 3 },

  // === Meridian Luxe — passenger/luxury ===
  { id: 'porpoise', name: 'Porpoise', manufacturer: 'Meridian Luxe', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 14, cost: 1200000, multirole: false, class: 2 },
  { id: 'dolphin_mk2', name: 'Narwhal Mk-II', manufacturer: 'Meridian Luxe', cargoCapacity: 8, fuelCapacity: 16, jumpRange: 16, cost: 2800000, multirole: true, class: 2 },
  { id: 'beluga_jr', name: 'Cachalot Jr', manufacturer: 'Meridian Luxe', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 15, cost: 28000000, multirole: false, class: 3 },
  { id: 'narwhal_mk2', name: 'Narwhal Mk-III', manufacturer: 'Meridian Luxe', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 17, cost: 32000000, multirole: false, class: 3 },
  { id: 'cachalot_mk2', name: 'Cachalot Mk-II', manufacturer: 'Meridian Luxe', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 16, cost: 38000000, multirole: false, class: 3 },
  { id: 'manatee', name: 'Manatee', manufacturer: 'Meridian Luxe', cargoCapacity: 14, fuelCapacity: 32, jumpRange: 14, cost: 36000000, multirole: false, class: 3 },
  { id: 'orca_mk2', name: 'Cachalot Mk-III', manufacturer: 'Meridian Luxe', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 17, cost: 52000000, multirole: false, class: 3 },
  { id: 'leviathan_liner', name: 'Leviathan Cruiser Mk-II', manufacturer: 'Meridian Luxe', cargoCapacity: 16, fuelCapacity: 64, jumpRange: 16, cost: 92000000, multirole: false, class: 4 },
  { id: 'blue_whale', name: 'Blue Whale', manufacturer: 'Meridian Luxe', cargoCapacity: 20, fuelCapacity: 64, jumpRange: 14, cost: 120000000, multirole: false, class: 4 },
  { id: 'royal_narwhal', name: 'Royal Narwhal', manufacturer: 'Meridian Luxe', cargoCapacity: 18, fuelCapacity: 64, jumpRange: 18, cost: 140000000, multirole: false, class: 4 },

  // === Solaris Dynasty — imperial ===
  { id: 'imperial_eagle', name: 'Dynast Raptor', manufacturer: 'Solaris Dynasty', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 11, cost: 58000, multirole: false, class: 1 },
  { id: 'dynast_scout', name: 'Dynast Pathfinder', manufacturer: 'Solaris Dynasty', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 13, cost: 82000, multirole: true, class: 1 },
  { id: 'dynast_courier_mk2', name: 'Dynast Herald Mk-II', manufacturer: 'Solaris Dynasty', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 14, cost: 6200000, multirole: true, class: 2 },
  { id: 'imperial_hawk', name: 'Dynast Hawk', manufacturer: 'Solaris Dynasty', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 12, cost: 4800000, multirole: false, class: 2 },
  { id: 'dynast_shuttle', name: 'Dynast Shuttle', manufacturer: 'Solaris Dynasty', cargoCapacity: 12, fuelCapacity: 16, jumpRange: 13, cost: 2600000, multirole: false, class: 2 },
  { id: 'imperial_falcon', name: 'Dynast Drake', manufacturer: 'Solaris Dynasty', cargoCapacity: 8, fuelCapacity: 32, jumpRange: 14, cost: 5800000, multirole: false, class: 2 },
  { id: 'dynast_clipper_mk2', name: 'Dynast Schooner Mk-II', manufacturer: 'Solaris Dynasty', cargoCapacity: 38, fuelCapacity: 32, jumpRange: 15, cost: 28000000, multirole: true, class: 3 },
  { id: 'imperial_raven', name: 'Dynast Raven', manufacturer: 'Solaris Dynasty', cargoCapacity: 8, fuelCapacity: 32, jumpRange: 13, cost: 26000000, multirole: false, class: 3 },
  { id: 'dynast_palace', name: 'Dynast Palace', manufacturer: 'Solaris Dynasty', cargoCapacity: 16, fuelCapacity: 32, jumpRange: 15, cost: 62000000, multirole: false, class: 3 },
  { id: 'dynast_sovereign_mk2', name: 'Dynast Sovereign Mk-II', manufacturer: 'Solaris Dynasty', cargoCapacity: 130, fuelCapacity: 64, jumpRange: 17, cost: 240000000, multirole: true, class: 4 },

  // === Coalition / Alliance ===
  { id: 'coalition_scout', name: 'Coalition Pathfinder', manufacturer: 'Orion Heavy', cargoCapacity: 8, fuelCapacity: 16, jumpRange: 18, cost: 3200000, multirole: true, class: 2 },
  { id: 'coalition_fighter', name: 'Coalition Fighter', manufacturer: 'Orion Heavy', cargoCapacity: 4, fuelCapacity: 16, jumpRange: 11, cost: 2800000, multirole: false, class: 2 },
  { id: 'coalition_ranger', name: 'Coalition Ranger', manufacturer: 'Orion Heavy', cargoCapacity: 36, fuelCapacity: 32, jumpRange: 16, cost: 24000000, multirole: true, class: 3 },
  { id: 'coalition_warden', name: 'Coalition Warden', manufacturer: 'Orion Heavy', cargoCapacity: 10, fuelCapacity: 32, jumpRange: 13, cost: 22000000, multirole: false, class: 3 },
  { id: 'coalition_bastion', name: 'Coalition Bastion Mk-II', manufacturer: 'Orion Heavy', cargoCapacity: 140, fuelCapacity: 64, jumpRange: 11, cost: 110000000, multirole: false, class: 4 },

  // === Independent / Specialty ===
  { id: 'sirius_explorer', name: 'Proxima Surveyor', manufacturer: 'Proxima Corp', cargoCapacity: 14, fuelCapacity: 32, jumpRange: 23, cost: 8800000, multirole: true, class: 2 },
  { id: 'omega_courier', name: 'Omega Herald', manufacturer: 'Omega Corp', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 13, cost: 48000, multirole: true, class: 1 },
  { id: 'sirius_trader', name: 'Proxima Trader', manufacturer: 'Proxima Corp', cargoCapacity: 48, fuelCapacity: 32, jumpRange: 15, cost: 26000000, multirole: false, class: 3 },
  { id: 'omega_interceptor', name: 'Omega Interceptor', manufacturer: 'Omega Corp', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 11, cost: 62000, multirole: false, class: 1 },
  { id: 'sirius_liner', name: 'Proxima Cruiser', manufacturer: 'Proxima Corp', cargoCapacity: 12, fuelCapacity: 32, jumpRange: 16, cost: 34000000, multirole: false, class: 3 },
  { id: 'void_prospector', name: 'Void Surveyor', manufacturer: 'Independent', cargoCapacity: 20, fuelCapacity: 16, jumpRange: 14, cost: 3600000, multirole: false, class: 2 },
  { id: 'star_drifter', name: 'Star Drifter', manufacturer: 'Independent', cargoCapacity: 30, fuelCapacity: 32, jumpRange: 24, cost: 38000000, multirole: true, class: 3 },
  { id: 'nova_hauler', name: 'Nova Freighter', manufacturer: 'Independent', cargoCapacity: 72, fuelCapacity: 32, jumpRange: 13, cost: 18000000, multirole: false, class: 3 },
];

// Base ship roster — core ships always available
const BASE_SHIP_TYPES = [
  { id: 'sidewinder', name: 'Sparrowhawk Mk-I', manufacturer: 'Drake-Voss', cargoCapacity: 4, fuelCapacity: 8, jumpRange: 8, cost: 0, multirole: true, class: 1 },
  { id: 'hauler', name: 'Packmule', manufacturer: 'Orion Heavy', cargoCapacity: 22, fuelCapacity: 16, jumpRange: 10, cost: 52000, multirole: false, class: 1 },
  { id: 'cobra', name: 'Drake Mk-III', manufacturer: 'Drake-Voss', cargoCapacity: 18, fuelCapacity: 16, jumpRange: 12, cost: 350000, multirole: true, class: 2 },
  { id: 'type6', name: 'Caravan Mk-VI', manufacturer: 'Orion Heavy', cargoCapacity: 50, fuelCapacity: 32, jumpRange: 15, cost: 1000000, multirole: false, class: 2 },
  { id: 'diamondback', name: 'Kingfisher Surveyor', manufacturer: 'Orion Heavy', cargoCapacity: 16, fuelCapacity: 32, jumpRange: 20, cost: 1900000, multirole: true, class: 2 },
  { id: 'asp', name: 'Heron Surveyor', manufacturer: 'Orion Heavy', cargoCapacity: 28, fuelCapacity: 32, jumpRange: 18, cost: 6600000, multirole: true, class: 2 },
  { id: 'type7', name: 'Caravan Mk-VII', manufacturer: 'Orion Heavy', cargoCapacity: 96, fuelCapacity: 32, jumpRange: 14, cost: 17000000, multirole: false, class: 3 },
  { id: 'python', name: 'Albatross', manufacturer: 'Drake-Voss', cargoCapacity: 56, fuelCapacity: 32, jumpRange: 16, cost: 56000000, multirole: true, class: 3 },
  { id: 'type9', name: 'Caravan Mk-IX', manufacturer: 'Orion Heavy', cargoCapacity: 220, fuelCapacity: 64, jumpRange: 10, cost: 78000000, multirole: false, class: 4 },
  { id: 'anaconda', name: 'Roc', manufacturer: 'Drake-Voss', cargoCapacity: 114, fuelCapacity: 64, jumpRange: 18, cost: 146000000, multirole: true, class: 4 },
  { id: 'eagle', name: 'Peregrine Mk-II', manufacturer: 'Sentinel Forge', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 7, cost: 44800, multirole: true, class: 1 },
  { id: 'adder', name: 'Osprey', manufacturer: 'Kepler Aeroworks', cargoCapacity: 6, fuelCapacity: 8, jumpRange: 10, cost: 87200, multirole: true, class: 1 },
  { id: 'viper', name: 'Shrike Mk-III', manufacturer: 'Drake-Voss', cargoCapacity: 2, fuelCapacity: 8, jumpRange: 9, cost: 143000, multirole: false, class: 1 },
  { id: 'cobramk4', name: 'Drake Mk-IV', manufacturer: 'Drake-Voss', cargoCapacity: 20, fuelCapacity: 16, jumpRange: 11, cost: 745000, multirole: true, class: 2 },
  { id: 'dolphin', name: 'Narwhal', manufacturer: 'Meridian Luxe', cargoCapacity: 6, fuelCapacity: 16, jumpRange: 15, cost: 1500000, multirole: true, class: 2 },
  { id: 'cobramk5', name: 'Drake Mk-V', manufacturer: 'Drake-Voss', cargoCapacity: 18, fuelCapacity: 16, jumpRange: 13, cost: 3900000, multirole: true, class: 2 },
  { id: 'federal_dropship', name: 'Republic Trooper', manufacturer: 'Sentinel Forge', cargoCapacity: 6, fuelCapacity: 32, jumpRange: 12, cost: 4900000, multirole: false, class: 3 },
  { id: 'vulture', name: 'Raven', manufacturer: 'Sentinel Forge', cargoCapacity: 2, fuelCapacity: 32, jumpRange: 11, cost: 5100000, multirole: false, class: 2 },
  { id: 'imperial_courier', name: 'Dynast Herald', manufacturer: 'Solaris Dynasty', cargoCapacity: 8, fuelCapacity: 32, jumpRange: 13, cost: 5400000, multirole: true, class: 2 },
  { id: 'mandalay', name: 'Wanderer', manufacturer: 'Kepler Aeroworks', cargoCapacity: 20, fuelCapacity: 32, jumpRange: 22, cost: 18500000, multirole: true, class: 2 },
  { id: 'alliance_chieftain', name: 'Coalition Flagship', manufacturer: 'Orion Heavy', cargoCapacity: 2, fuelCapacity: 32, jumpRange: 13, cost: 19000000, multirole: false, class: 3 },
  { id: 'federal_assault', name: 'Republic Vanguard', manufacturer: 'Sentinel Forge', cargoCapacity: 4, fuelCapacity: 32, jumpRange: 12, cost: 19800000, multirole: false, class: 3 },
  { id: 'imperial_clipper', name: 'Dynast Schooner', manufacturer: 'Solaris Dynasty', cargoCapacity: 34, fuelCapacity: 32, jumpRange: 14, cost: 22300000, multirole: true, class: 3 },
  { id: 'alliance_crusader', name: 'Coalition Paladin', manufacturer: 'Orion Heavy', cargoCapacity: 4, fuelCapacity: 32, jumpRange: 12, cost: 22800000, multirole: false, class: 3 },
  { id: 'alliance_challenger', name: 'Coalition Titan', manufacturer: 'Orion Heavy', cargoCapacity: 6, fuelCapacity: 32, jumpRange: 13, cost: 30800000, multirole: false, class: 3 },
  { id: 'type8', name: 'Caravan Mk-VIII', manufacturer: 'Orion Heavy', cargoCapacity: 76, fuelCapacity: 32, jumpRange: 15, cost: 36000000, multirole: false, class: 3 },
  { id: 'krait_phantom', name: 'Harrier Wraith', manufacturer: 'Drake-Voss', cargoCapacity: 14, fuelCapacity: 32, jumpRange: 17, cost: 37300000, multirole: true, class: 2 },
  { id: 'krait_mk2', name: 'Harrier Mk-II', manufacturer: 'Drake-Voss', cargoCapacity: 18, fuelCapacity: 32, jumpRange: 16, cost: 45300000, multirole: true, class: 2 },
  { id: 'orca', name: 'Cachalot', manufacturer: 'Meridian Luxe', cargoCapacity: 8, fuelCapacity: 32, jumpRange: 15, cost: 48500000, multirole: false, class: 3 },
  { id: 'mamba', name: 'Condor', manufacturer: 'Kepler Aeroworks', cargoCapacity: 2, fuelCapacity: 32, jumpRange: 12, cost: 56500000, multirole: false, class: 2 },
  { id: 'python_mk2', name: 'Albatross Mk-II', manufacturer: 'Drake-Voss', cargoCapacity: 20, fuelCapacity: 32, jumpRange: 14, cost: 75000000, multirole: false, class: 3 },
  { id: 'beluga', name: 'Leviathan Cruiser', manufacturer: 'Meridian Luxe', cargoCapacity: 12, fuelCapacity: 64, jumpRange: 14, cost: 85000000, multirole: false, class: 3 },
  { id: 'type10', name: 'Bastion Mk-X', manufacturer: 'Orion Heavy', cargoCapacity: 128, fuelCapacity: 64, jumpRange: 9, cost: 125000000, multirole: false, class: 4 },
  { id: 'federal_corvette', name: 'Republic Dreadnought', manufacturer: 'Sentinel Forge', cargoCapacity: 16, fuelCapacity: 64, jumpRange: 15, cost: 190000000, multirole: false, class: 4 },
  { id: 'imperial_cutter', name: 'Dynast Sovereign', manufacturer: 'Solaris Dynasty', cargoCapacity: 120, fuelCapacity: 64, jumpRange: 16, cost: 210000000, multirole: true, class: 4 },
];

export const SHIP_TYPES = [...BASE_SHIP_TYPES, ...ADDITIONAL_SHIPS];